### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by zakirkun** [irsyaadbp/Point-Of-Sales-API#9]
(node:6176) UnhandledPromiseRejectionWarning: ReferenceError: s is not defined
    at exports.newOrder (C:\Users\Public\project\Point-Of-Sales-API\src\Controllers\order.js:35:75)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:6176) UnhandledPromiseRejectionWarning: Unhandled promise rejection.

**Comment by irsyaadbp** [comment]
hello can you explain what the condition when you get the error?
